name: Super-Linter

on:
  push:
    branches:
      - 'feature/RND-123-add-new-feature'

 
jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_PYTHON_PYLINT: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Declare some variables
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag davidalkobi/app:${{ env.sha_short }}
  
